services:
  proxy-chatgpt:
    container_name: proxy-chatgpt
    environment:
     - OPENAI_API_KEY=$OPENAI_API_KEY
     - LOG_PATH=/var/log/proxy-chatgpt/proxy_chatgpt.log
    network_mode: host
    image: proxy-chatgpt
    restart: always
    volumes:
    - /root/zhouheng/proxy-chatgpt:/opt/proxy-chatgpt
    - /root/zhouheng/log:/var/log/proxy-chatgpt
    - /root/zhouheng/config:/etc/proxy-chatgpt
  pc-mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: pc-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE=pchat
    image: mysql:5.7
    ports:
    - 9536:3306
    restart: always
    volumes:
    - pc-mysql:/var/lib/mysql
volumes:
  pc-mysql:
    name: pc-mysql
version: '2.3'
