services:
  proxy-chatgpt:
    container_name: proxy-chatgpt
    environment:
     - OPENAI_API_KEY=$OPENAI_API_KEY
     - LOG_PATH=/var/log/proxy-chatgpt/proxy_chatgpt.log
    network_mode: host
    image: proxy-chatgpt
    restart: always
    volumes:
    - /root/zhouheng/proxy-chatgpt:/opt/proxy-chatgpt
    - /root/zhouheng/log:/var/log/proxy-chatgpt
version: '2.3'
